# Generated by Selenium IDE
#import pytest
import requests
from requests.api import head 
url = 'https://kairos.unifi.it/agendaweb/index.php?view=prenotalezione&include=prenotalezione&_lang=it'
    

import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver import Chrome
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support import wait
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from bs4 import BeautifulSoup


driver = webdriver.Firefox()
driver.implicitly_wait(10)

# Test name: Untitled
# Step # | name | target | value
# 1 | open | https://kairos.unifi.it/auth/auth_app_test.php?response_type=token&client_id=client&redirect_uri=https://kairos.unifi.it/agendaweb/index.php%3Fview=login&scope=openid+profile |
driver.get("https://kairos.unifi.it/auth/auth_app_test.php?response_type=token&client_id=client&redirect_uri=https://kairos.unifi.it/agendaweb/index.php%3Fview=login&scope=openid+profile")
# 2 | type | id=password | Aereoplano13
driver.find_element(By.ID, "password").send_keys("Aereoplano13")
# 3 | type | id=username | 7046719
driver.find_element(By.ID, "username").send_keys("7046719")
# 4 | click | name=_eventId_proceed |
driver.find_element(By.NAME, "_eventId_proceed").click()
# 5 | click | linkText=Nuova prenotazione |
print("ciaoooooo")

print(driver.get_cookies())
id_sessione = driver.get_cookie("JSESSIONID")
auth_shibboleth = driver.get_cookie("shib_idp_session")

print("eiiii")
# 6 click nella sezione lista lezioni
#driver.find_element_by_xpath(
 #   "/html/body/div[4]/div[4]/div[3]/div/div[2]/div[1]/div/div[6]/div/div[2]/div[2]/ul/li[1]/a").click()
#lezioni = driver.find_elements(By.TAG_NAME, "a")
#for l in lezioni:
#    print(l.text)


cookies_raw = driver.get_cookies()

#print(filter("shibsesion", driver.get_cookies()))

#print("ciao ora provo della roba")
# print(driver.get_cookie("shibsession"))


print("###################")
print(cookies_raw[0])

primo_cookie = cookies_raw[0]
print("###################")
print(primo_cookie["name"])
print("###################")
print(primo_cookie["value"])
print("###################")
secondo_cookie = cookies_raw[1]
print(secondo_cookie)



headers = {'Connection': 'keep-alive',
 'Pragma': 'no-cache',
 'Cache-Control': 'no-cache',
 'Upgrade-Insecure-Requests': '1',
 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36',
 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
 'Sec-GPC': '1',
 'Sec-Fetch-Site': 'same-origin',
 'Sec-Fetch-Mode': 'navigate',
 'Sec-Fetch-User': '?1',
 'Sec-Fetch-Dest': 'document',
 'Referer': 'https://kairos.unifi.it/agendaweb/index.php?view=prenotalezione&include=prenotalezione_home&_lang=it',
 'Accept-Encoding': 'gzip, deflate, br',
 'Accept-Language': 'it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7',
 'Cookie': 'PHPSESSID=qualcosa; shibsession=asasa'
 }
#2v3t0h74gantu09f84n7v7b9i4
#_shibsession_6b6169726f732e756e6966692e697468747470733a2f2f6b6169726f732e756e6966692e69742f73686962626f6c657468

headers["Cookie"] = primo_cookie["name"] + "=" + primo_cookie["value"] + "; " + secondo_cookie["name"] + "=" + secondo_cookie["value"]





req = requests.get(url=url, headers=headers)



print("------------------------------------")

print(req.status_code)
print(req.headers)
print(req.text)
print(headers)

print("------------------------------------")


##############################################

