# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Firefox()

  # Test name: trova lista lezioni
  # Step # | name | target | value
  # 1 | open | https://kairos.unifi.it/agendaweb/index.php?view=login&include=login&from=logout&_lang= |
driver.get(
       "https://kairos.unifi.it/agendaweb/index.php?view=login&include=login&from=logout&_lang=")
   # 2 | setWindowSize | 550x691 |
driver.set_window_size(550, 691)
    # 3 | click | css=.fa-home |
driver.find_element(By.CSS_SELECTOR, ".fa-home").click()
    # 4 | click | linkText=Nuova prenotazione |
driver.find_element(By.LINK_TEXT, "Nuova prenotazione").click()
    # 5 | click | css=.form-group:nth-child(5) .slider |
driver.find_element(   By.CSS_SELECTOR, ".form-group:nth-child(5) .slider").click()
    # 6 | click | css=.form-group:nth-child(6) .slider |
driver.find_element(    By.CSS_SELECTOR, ".form-group:nth-child(6) .slider").click()
    # 7 | click | id=oauth_btn |
driver.find_element(By.ID, "oauth_btn").click()
driver.find_element(By.LINK_TEXT, "Le mie prenotazioni").click()
    # 9 | click | linkText=Nuova prenotazione |
driver.find_element(By.LINK_TEXT, "Nuova prenotazione").click()
    # 10 | click | css=#\31 33787 > span |
driver.find_element(By.CSS_SELECTOR, "#\\31 33787 > span").click()
    # 11 | click | css=.normal-button |
driver.find_element(By.CSS_SELECTOR, ".normal-button").click()
    # 12 | click | xpath=(//div[@id='box_']/div[2]/div/div[2]/span)[21] |
driver.find_element( By.XPATH, "(//div[@id=\'box_\']/div[2]/div/div[2]/span)[21]").click()
    # 13 | click | xpath=(//div[@id='box_']/div[2]/div/div[2]/span)[21] |
driver.find_element(            By.XPATH, "(//div[@id=\'box_\']/div[2]/div/div[2]/span)[21]").click()
    # 14 | doubleClick | xpath=(//div[@id='box_']/div[2]/div/div[2]/span)[21] |
element = driver.find_element(        By.XPATH, "(//div[@id=\'box_\']/div[2]/div/div[2]/span)[21]")
actions = ActionChains(driver)
actions.double_click(element).perform()
    # 15 | click | xpath=(//div[@id='box_']/div[2]/div/div[2]/span[4])[5] |
driver.find_element(        By.XPATH, "(//div[@id=\'box_\']/div[2]/div/div[2]/span[4])[5]").click()
    # 16 | click | xpath=(//div[@id='box_']/div[2]/div/div[2]/span)[28] |
driver.find_element(        By.XPATH, "(//div[@id=\'box_\']/div[2]/div/div[2]/span)[28]").click()
    # 17 | click | xpath=(//div[@id='box_']/div[2]/div/div[2]/span)[17] |
driver.find_element(        By.XPATH, "(//div[@id=\'box_\']/div[2]/div/div[2]/span)[17]").click()
    # 18 | click | xpath=(//div[@id='box_']/div[2]/div/div[2]/span[4])[3] |
driver.find_element(        By.XPATH, "(//div[@id=\'box_\']/div[2]/div/div[2]/span[4])[3]").click()
    # 19 | click | xpath=(//div[@id='box_']/div[2]/div/div[2]/span)[11] |
driver.find_element(        By.XPATH, "(//div[@id=\'box_\']/div[2]/div/div[2]/span)[11]").click()
    # 20 | click | xpath=(//div[@id='box_']/div[2]/div/div[2]/span)[7] |
driver.find_element(        By.XPATH, "(//div[@id=\'box_\']/div[2]/div/div[2]/span)[7]").click()
    # 21 | click | xpath=//div[@id='box_']/div[2]/div/div[2]/span[4] |
driver.find_element(        By.XPATH, "//div[@id=\'box_\']/div[2]/div/div[2]/span[4]").click()
    # 22 | click | xpath=//div[@id='box_']/div[2]/div/div[2]/span |
driver.find_element(        By.XPATH, "//div[@id=\'box_\']/div[2]/div/div[2]/span").click()

element = driver.find_element(By.TAG_NAME, 'div')

    # Get all the elements available with tag name 'p'
elements = element.find_elements(By.TAG_NAME, 'p')
for e in elements:
        print(e.text)
